GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/683b1073bdc4ce0a3aa44e96

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Amazing Person 2",
    "subscribedToChannel": "Code Dynasty Studios [CDS]"
}

###

DELETE  http://localhost:3000/subscribers/683b2cfc7c12fb6ab374f2fa

### 

PATCH   http://localhost:3000/subscribers/683b081ff60510b24a83c6a9
Content-Type: application/json

{
    "name": "Dynasty Dagreat",
    "subscribedToChannel": "Code Dynasty Studios [CDS] 2.0"
}

### for followers

GET http://localhost:3000/followers

###
GET http://localhost:3000/followers/683d4b5183b75a6c9ee17108

### 
POST http://localhost:3000/followers
Content-Type: application/json

{
    "name": "Abiodun",
    "followedToPage": "Emmanuel.9944"
}


### 

PATCH http://localhost:3000/followers/683d3dc6dee13228aa5aaa43
Content-Type: application/json

{
    "name": "Dynasty"
}

###
DELETE http://localhost:3000/followers/683d3d5b1ebd640e2fccd3ab


### For connections

GET http://localhost:3000/connections

###

GET http://localhost:3000/connections/683d787c1510d6fcccf902a5


### 

POST http://localhost:3000/connections
Content-Type: application/json

{
    "name": "Ajayi",
    "connectedToAccount": "Emmanuel"
}

###
PATCH http://localhost:3000/connections/683d77d1207a2898df0d3e5b
Content-Type: application/json

{
    "name": "Dynasty"
}